version: "3.7"

services:
  redis:
    image: redis
    container_name: redisdb
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data/

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  redis:
  mongo:


