// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateURL struct {
	URL string `json:"url"`
}

type UpdateURL struct {
	Code     *string `json:"code"`
	URL      *string `json:"url"`
	ShortURL *string `json:"shortUrl"`
}

type URL struct {
	Code     string `json:"code"`
	URL      string `json:"url"`
	ShortURL string `json:"shortUrl"`
}
